## Settings
title: PERSONAL HOMEPAGE
owner: "Huiyu(Joey) Zhang"
url: "https://Jooooooooooey.github.io"
baseurl: ""
permalink: /:title/
description: "This is description"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "hz2497@columbia.edu"
github: "Jooooooooooey"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "MAY THE FORCE BE WITH YOU"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
