## Settings
title: Huiyu(Joey) Zhang
owner: "DeerRIDER"
url: "https://Jooooooooooey.github.io"
baseurl: "/Huiyu(Joey) Zhang"
permalink: /:title/
description: "This is Joey's personal web "
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "hz2497@columbia.edu"
github: "/Jooooooooooey"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by DeerRIDER, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "This is bgText"
